# Elasticsearch est comme un bibliothécaire super rapide qui stocke
# les logs et peut les retrouver en quelques secondes grâce à un système
# de recherche très puissant. C'est là où les logs sont enregistrés et
# indexés pour que tu puisses les consulter facilement.

FROM baseImage
